/**
 * Segmented gallery stills — portfolio renders self-hosted under `public/gallery/portfolio/`.
 * Legacy Waytowebs stills retained as supplementary frames where noted.
 */
import { PORTFOLIO_GALLERY } from "./vivid-reference";

const P = PORTFOLIO_GALLERY;

export const portfolioSegmentedGallery = [
  `${P}/living-room-tv-feature-wall.png`,
  `${P}/modern-dining-room-green-chairs.png`,
  `${P}/living-room-sectional-circular-art.png`,
  `${P}/living-room-red-bird-art.png`,
  `${P}/modular-kitchen-wood-beige.png`,
  `${P}/galley-kitchen-samsung-fridge.png`,
  `${P}/living-room-kitchenette-open-plan.png`,
  `${P}/master-bedroom-geometric-panel.png`,
  `${P}/bedroom-wardrobe-tinted-glass.png`,
  `${P}/bedroom-tan-headboard-wardrobe.png`,
] as const;

export const delhiKitchenSegmentedGallery = [
  `${P}/modular-kitchen-wood-beige.png`,
  `${P}/galley-kitchen-samsung-fridge.png`,
  `${P}/living-room-kitchenette-open-plan.png`,
  "/gallery/delhi-kitchen/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.11.png",
  "/gallery/delhi-kitchen/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.9.png",
  "/gallery/delhi-kitchen/Villa-193-East-Indukuri-Lakeshore-Rnders-revised2.png",
  "/gallery/delhi-kitchen/Villa-193-East-Indukuri-Lakeshore-Rnders-revised2.2.png",
  "/gallery/delhi-kitchen/Villa-193-East-Indukuri-Lakeshore-Rnders1-1.png",
  "/gallery/delhi-kitchen/Villa-193-East-Indukuri-Lakeshore-Rnders-revised2.3.png",
  "/gallery/delhi-kitchen/Villa-193-East-Indukuri-Lakeshore-Rnders-revised442.png",
  "/gallery/delhi-kitchen/Villa-193-East-Indukuri-Lakeshore-Rnders-revised43444.png",
] as const;

export const josephKitchenSegmentedGallery = [
  `${P}/galley-kitchen-samsung-fridge.png`,
  `${P}/modular-kitchen-wood-beige.png`,
  `${P}/living-room-kitchenette-open-plan.png`,
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/kitchen-option-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/kitchen-option-2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/kitchen-option-3.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/kitchen-option-4.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/kitchen-option-5.jpg",
] as const;

export const sheebaVilla157SegmentedGallery = [
  `${P}/master-bedroom-geometric-panel.png`,
  `${P}/bedroom-wardrobe-tinted-glass.png`,
  `${P}/bedroom-tan-headboard-wardrobe.png`,
  `${P}/living-room-sectional-circular-art.png`,
  `${P}/living-room-tv-feature-wall.png`,
  `${P}/modern-dining-room-green-chairs.png`,
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/ground-floor-Secondary-bedroom-20250316-144027-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/ground-floor-Secondary-bedroom-20250316-144029-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/ground-floor-Secondary-bedroom-20250316-144414-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/ground-floor-Unnamed-20250316-131125-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/ground-floor-Unnamed-20250316-140711-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Customized-20250318-091719-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/ground-floor-Unnamed-20250316-140720-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Living-Dining-Room-20250320-012005-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Customized-20250318-091722-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Unnamed-20250507-222909.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Walk-in-wardrobe-20250505-072920.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Unnamed-20250505-065527-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Customized-20250319-231955-1-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Living-Dining-Room-20250319-223137-1-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Living-Dining-Room-20250319-223146-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Living-Dining-Room-20250320-012005-1-2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/3.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/4.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/5-scaled.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/6-scaled.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/7-scaled.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/8.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/9.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/10.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/11-scaled.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/12-scaled.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/13-scaled.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/14-scaled.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/0-scaled.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Customized-20250331-011415.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Unnamed-20250330-214011.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Sheeba-Maam-Villa-157-indukuri-Living-Dining-Room-20250319-223137-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/sheeba-revised2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/sheeba-revised-2.2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/sheeba-revised-2.6.jpg",
] as const;

export const villa173WestSegmentedGallery = [
  `${P}/living-room-tv-feature-wall.png`,
  `${P}/living-room-sectional-circular-art.png`,
  `${P}/living-room-red-bird-art.png`,
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-12.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-9-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-8-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders7-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-6-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-4-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-3-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-2-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-1-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-11.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders10.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-5.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-1.6.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-1.5.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-1.4.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-1.3.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-1.2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-1.1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-2.4.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-2.3.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-2.2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-2.1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-3.6.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-3.5.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-3.4.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-3.3.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-3.2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-3.1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-173-West-Indukuri-Lakeshore-Renders-revised-3.jpg",
] as const;

export const villa193EastSegmentedGallery = [
  `${P}/living-room-sectional-circular-art.png`,
  `${P}/living-room-red-bird-art.png`,
  `${P}/modern-dining-room-green-chairs.png`,
  `${P}/living-room-kitchenette-open-plan.png`,
  `${P}/master-bedroom-geometric-panel.png`,
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-5-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-4-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-3-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders2-2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders1-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.14.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.13.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.12.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.11.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.9.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.7.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.6.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.5.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.3-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.4-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised1.8-1.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised2.3.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised2.2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised2.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised43444.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised442.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/41.jpg",
  "https://waytowebs.in/vivid/wp-content/uploads/2026/04/Villa-193-East-Indukuri-Lakeshore-Rnders-revised44.jpg",
] as const;
